package br.com.luizalabs.wishlist.domain.response;

import br.com.luizalabs.wishlist.domain.Wishlist;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public class WishlistResponse {

    @JsonIgnore
    private final Wishlist wishlist;

    @ApiModelProperty("Wishlist autogenerated id")
    public String getId() {
        return wishlist.getId().toHexString();
    }

    @ApiModelProperty("Wishlist's name")
    public String getName() {
        return wishlist.getName();
    }
}
